Add index.html file and linters configuration
Artufelii/microverse-hello-world pull request #1
Opened 2023-03-22 01:47 UTC by Artufelii

Create of index.html file with initial code, and alse add the linters configuration necessary for the tests on HTML and CSS

2023-03-22 03:05 UTC, didierganthier requested changes
Hi @Artufelii ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/3oEduMcvxTNPlGuhH2/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Added `.gitignore` ✔️ 
- Used README template ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-03-22 03:05 UTC, didierganthier commented on README.md
> +- [👥 Authors](#authors)
Well done on using the README template provided by Microverse 💯 but several sections seem to have been removed from the `Table of Contents` 📄 these sections were required, only the `FAQ` is optional and can be removed. Make sure to add the other sections to make the README complete just like the [template](https://github.com/microverseinc/readme-template/blob/master/README.md) 🤓

2023-03-22 03:05 UTC, didierganthier commented on .github/workflows/linters.yml
> +          node-version: "18.x"
Nice work on the linters ✅ but in order to fix the failing lighthouse ❌ you could try replacing that line by this:
```
node-version: "12.x"
```
The lighthouse might get fixed then 😉

2023-03-22 03:20 UTC, Artufelii commented
Ok thank your for your help and I will do the changes

El mar, 21 mar 2023 a las 21:06, Didier Peran Ganthier (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> Hi @Artufelii <https://github.com/Artufelii> ,
>
> 🎉 Good job so far! You're making great progress on this project, but
> there are still a few areas that need attention before we can move on to
> the next step.
>
>
> <https://camo.githubusercontent.com/7629b0b5844650071258f57d3b0b17644ccdf589a8b2fb9da176cdaabe587bb0/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f4564754d637678544e506c47756848322f67697068792e676966>
> Highlights
>
>    - Descriptive PR ✔️
>    - Added .gitignore ✔️
>    - Used README template ✔️
>
> Required Changes 🛠
>
>    - Please review the comments under the review for specific changes
>    that still need to be made.
>
> Optional Suggestions 💡
>
>    - While these comments with the [OPTIONAL] prefix won't prevent the
>    approval of this pull request, I strongly recommend taking them into
>    account as they can improve your code.
>
> 🚀 Keep pushing forward, you're almost there! If you have any questions
> or need clarification on anything, feel free to leave a comment in the pull
> request thread and don't forget to tag me so I'll receive the notification.
>
> *Please note*
>
>    - To avoid confusion and delays, please do not open a new pull request
>    for re-reviews. Use the same pull request submitted for the first review,
>    unless otherwise instructed.
>
> ------------------------------
>
> As per the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561>, you
> have a limited number of reviews per project. If you feel that the code
> review was unfair, you can request a second opinion using this form
> <https://airtable.com/shrQAqnBwek5a0O0s>.
>
> Cheers and happy coding! 👏👏👏
> ------------------------------
>
> In README.md
> <https://github.com/Artufelii/microverse-hello-world/pull/1#discussion_r1144173746>
> :
>
> > +# 📗 Table of Contents
> +
> +- [📖 About the Project](#about-project)
> +  - [🛠 Built With](#built-with)
> +    - [Tech Stack](#tech-stack)
> +
> +- [👥 Authors](#authors)
>
> Well done on using the README template provided by Microverse 💯 but
> several sections seem to have been removed from the Table of Contents 📄
> these sections were required, only the FAQ is optional and can be
> removed. Make sure to add the other sections to make the README complete
> just like the template
> <https://github.com/microverseinc/readme-template/blob/master/README.md>
> 🤓
> ------------------------------
>
> In .github/workflows/linters.yml
> <https://github.com/Artufelii/microverse-hello-world/pull/1#discussion_r1144177450>
> :
>
> > +name: Linters
> +
> +on: pull_request
> +
> +env:
> +  FORCE_COLOR: 1
> +
> +jobs:
> +  lighthouse:
> +    name: Lighthouse
> +    runs-on: ubuntu-22.04
> +    steps:
> +      - uses: ***@***.***
> +      - uses: ***@***.***
> +        with:
> +          node-version: "18.x"
>
> Nice work on the linters ✅ but in order to fix the failing lighthouse ❌
> you could try replacing that line by this:
>
> node-version: "12.x"
>
> The lighthouse might get fixed then 😉
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Artufelii/microverse-hello-world/pull/1#pullrequestreview-1351642334>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5ZAQ2SJKVLJBPSDYDNBXTW5JUCBANCNFSM6AAAAAAWDGO55M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-22 03:50 UTC, Artufelii commented
I already do the changes on the README file and linters file, thanks for your help

2023-03-22 06:09 UTC, Shedrack-Sunday requested changes
Hi @Artufelii      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well implementing the requirements,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlights
✅All linters are checked

  
# Required Changes ♻️

- [x] I must admit you have really put in the effort so far in this project, however, the changes required below need to be implemented :
- You had a lot of commented guides from the template from the new addition you made. As guides, they should not be added to your project. Please check for a detailed review below 👍 


_check the comment section for a detailed review_ 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] You did well adding the other sections as suggested by the previous reviewer. however, kindly always delete the part with the `>` sign, as it's added to show you directions o what t add. This helps keep your code clean, and adhere to professionalism 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +> Add a link to your deployed project.
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Please revert to my detailed comment on line `42` on the comment here 👍

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +
- [ ] Nice one adding the MIT license 👏 . However, you need to have a file named `LICENSE` at the root of your project, with the content given on the README template, so the path here is not broken. 
-  [ ] Please do delete line `203`, as its meant to serve as a guide and not to be commented on your code 👍 . This keeps your code clean, and give a more professional feel

2023-03-22 06:09 UTC, Shedrack-Sunday commented on README.md
> +  - [Answer_2]
- [ ] The `FAQ` is the only optional section as said by your previous reviewer. if you don't intend to add to it, kindly delete the whole section. Else, I strongly advice you to add a possible question people might ask about your project

2023-03-22 19:39 UTC, Artufelii commented on README.md
> +  - [Answer_2]
thank you @Shedrack-Sunday I did the changes already

2023-03-23 15:38 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Artufelii, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 16:42 UTC, merged